//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        public string MAKH { get; set; }
        public string TENKH { get; set; }
        public string DCHI { get; set; }
        public string SDT { get; set; }
        public Nullable<System.DateTime> NGAYMUAHANG { get; set; }
        public string GIOITINH { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> NGAYNHAPKHACHHANG { get; set; }
        public string GHICHUDATHANG { get; set; }
        public Nullable<System.DateTime> NGAYCAPNHATLAIKHACHHANG { get; set; }
    }
}
