//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHMUCSANPHAM
    {
        public int MaDM { get; set; }
        public string TenDMSP { get; set; }
        public byte[] NgayTao { get; set; }
    }
}
