//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public string TacGia { get; set; }
        public string NamSX { get; set; }
        public string NhaSX { get; set; }
        public string LoaiSP { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public byte[] Created_at { get; set; }
        public string Noidung { get; set; }
    }
}
