//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        public string MATK { get; set; }
        public string SDT { get; set; }
        public string EMAIL { get; set; }
        public string MATKAU { get; set; }
        public string TENTK { get; set; }
        public Nullable<System.DateTime> NGAYTAONGUOIDUNG { get; set; }
        public Nullable<System.DateTime> NGAYCAPNHATNGUOIDUNG { get; set; }
        public string GHINHOCHUNGTHUCVANHOTAIKHOAN { get; set; }
    }
}
